import{a as q,S as T,i as P}from"./assets/vendor-a7b3a87b.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function n(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(t){if(t.ep)return;t.ep=!0;const r=n(t);fetch(t.href,r)}})();async function w(o,e,n){const s=new URLSearchParams({key:"44351431-da99bbc5aa576d6c36cc46a59",q:o,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:n,page:e});return(await q.get(`https://pixabay.com/api/?${s}`)).data}function L(o){return o.map(({webformatURL:e,largeImageURL:n,tags:s,likes:t,views:r,comments:i,downloads:O})=>`
        <li class="gallery-item">
      <a class="gallery-link" href="${n}" >
        <img
          src="${e}"
          alt="${s}" loading='lazy'width = "360" height = "152"
        /></a> 
      <div class="info">
      <p class="info-item"><b>likes:</b>"${t}"</p>
      <p class="info-item"><b>Views:</b>"${r}"</p>
      <p class="info-item"><b>Comments:</b>"${i}"</p>
      <p class="info-item"><b>Downloads:</b>"${O}"</p>
      </div>`).join(" ")}const $="/goit-js-hw-12/assets/alert-icon-40fa32d5.svg",u=document.querySelector(".btn-to-top");window.addEventListener("scroll",v);u.addEventListener("click",S);function v(){const o=window.pageYOffset,e=document.documentElement.clientHeight;o>e&&u.classList.add("visible"),o<e&&u.classList.remove("visible")}function S(){window.pageYOffset>0&&window.scrollTo({top:0,behavior:"smooth"})}const{form:h,gallery:g,loadMoreBtn:y,loadElem:E}={form:document.querySelector(".form"),gallery:document.querySelector(".gallery"),loadMoreBtn:document.querySelector(".js-load-btn"),loadElem:document.querySelector(".loader")};let l="",c=1,d=0;const f=15;let C=new T(".gallery-item a",{captions:!0,captionsData:"alt",captionDelay:250});v();S();h.addEventListener("submit",M);y.addEventListener("click",k);async function M(o){if(o.preventDefault(),window.scrollTo({top:0}),l=o.currentTarget.elements.searchQuery.value.trim(),!l){a("The search string cannot be empty. Please specify your search query.");return}c=1,B(),b();try{const e=await w(l,c,f);if(d=Math.ceil(e.totalHits/f),d===0){a("Sorry, there are no images matching your search query. Please try again!"),p(),m();return}const n=L(e.hits);g.innerHTML=n}catch{a("Something went wrong...")}p(),m(),h.reset()}async function k(){c+=1,b(),B();try{const o=await w(l,c,f),e=L(o.hits);g.insertAdjacentHTML("beforeend",e),C.refresh(),j()}catch{a("Something went wrong...")}p(),m(),h.reset()}function m(){c>=d?(b(),d&&a("We're sorry, but you've reached the end of search results.")):F()}function F(){y.classList.remove("hidden")}function b(){y.classList.add("hidden")}function a(o){P.error({title:"Error",backgroundColor:"#ef4040",messageColor:"#fff",messageSize:"16",imageWidth:302,close:!0,closeOnEscape:!0,closeOnClick:!0,progressBar:!0,progressBarColor:"#b51b1b",transitionIn:"flipInX",transitionOut:"flipOutX",position:"topRight",iconUrl:$,iconColor:"#FAFAFB",theme:"dark",message:o})}function B(){E.classList.remove("hidden")}function p(){E.classList.add("hidden")}function j(){const e=g.children[0].getBoundingClientRect().height;scrollBy({top:e*3,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
